const menuKey='crisp-live-menu-v1';
let products = (JSON.parse(localStorage.getItem(menuKey)||'[]')).filter(item=>item.available!==false).map(item=>({...item,desc:item.description||'',tag:item.tag||''}));
let cart = JSON.parse(localStorage.getItem('crisp-live-cart-v1') || '{}');
let favorites = JSON.parse(localStorage.getItem('crisp-live-favorites-v1') || '[]');
let activeCategory = 'all';
let favoritesOnly = false;
let discountRate = 0;
const $ = selector => document.querySelector(selector);
const currencyMap = { US:['USD','en-US','United States'], ZA:['ZAR','en-ZA','South Africa'], CA:['CAD','en-CA','Canada'], GB:['GBP','en-GB','United Kingdom'], AU:['AUD','en-AU','Australia'], IN:['INR','en-IN','India'], KE:['KES','en-KE','Kenya'], ZW:['USD','en-ZW','Zimbabwe'], JP:['JPY','ja-JP','Japan'], SG:['SGD','en-SG','Singapore'], AE:['AED','en-AE','United Arab Emirates'], DE:['EUR','de-DE','Germany'], FR:['EUR','fr-FR','France'], IT:['EUR','it-IT','Italy'], ES:['EUR','es-ES','Spain'], BR:['BRL','pt-BR','Brazil'], MX:['MXN','es-MX','Mexico'] };
const fallbackRates = { USD:1, CAD:1.37, GBP:.79, AUD:1.53, INR:83.1, JPY:149, SGD:1.34, AED:3.67, EUR:.92, BRL:5.45, MXN:18.2, ZAR:18.2, KES:129 };
const verifiedMarketPrices = { ZA:{bucket:199,sandwich:64,tenders:84,fries:45,burger:49,mac:35,biscuit:15,sundae:29} };
let locationState = JSON.parse(localStorage.getItem('crisp-location') || 'null') || {countryCode:'US',currency:'USD',locale:'en-US',label:'10001 · New York, NY',country:'United States',rate:1};
const money = value => new Intl.NumberFormat(locationState.locale,{style:'currency',currency:locationState.currency,maximumFractionDigits:locationState.currency === 'JPY' ? 0 : 2}).format(value * locationState.rate);
const unitPrice = product => locationState.marketPrices?.[product.id] ?? product.price * locationState.rate;
const localMoney = value => new Intl.NumberFormat(locationState.locale,{style:'currency',currency:locationState.currency,maximumFractionDigits:locationState.currency === 'JPY' ? 0 : 2}).format(value);
function currencyFor(countryCode, locale){ const entry = currencyMap[countryCode] || ['USD',locale || 'en-US',countryCode || 'United States']; return {countryCode:countryCode || 'US',currency:entry[0],locale:entry[1],country:entry[2]}; }
const savedCurrency = currencyFor(locationState.countryCode, locationState.locale);
if (locationState.currency !== savedCurrency.currency) locationState = {...locationState,...savedCurrency,rate:fallbackRates[savedCurrency.currency] || 1};
locationState.marketPrices = verifiedMarketPrices[locationState.countryCode] || null;
async function applyLocation(details){ const next = {...locationState,...currencyFor(details.countryCode,details.locale),label:details.label || locationState.label}; try { const response = await fetch('https://open.er-api.com/v6/latest/USD'); const rates = await response.json(); next.rate = rates.rates?.[next.currency] || fallbackRates[next.currency] || 1; } catch { next.rate = fallbackRates[next.currency] || 1; } next.marketPrices = verifiedMarketPrices[next.countryCode] || null; locationState = next; localStorage.setItem('crisp-location',JSON.stringify(locationState)); $('#locationBtn').innerHTML = `<span>⌖</span> ${locationState.label} <small>⌄</small>`; $('#deliveryLocation').textContent = locationState.label; updateCart(); renderProducts(document.querySelector('.category-tabs button.active')?.dataset.category || 'all'); }
async function detectLocation(){ const button = $('#locationBtn'); button.disabled = true; button.innerHTML = '<span>⌖</span> Finding you…'; const useLocale = () => { const locale = Intl.DateTimeFormat().resolvedOptions().locale || 'en-US'; const countryCode = locale.split('-')[1]?.toUpperCase() || 'US'; applyLocation({countryCode,locale,label:`Local prices · ${countryCode}`}); }; const useIp = () => fetch('https://ipapi.co/json/').then(response=>response.json()).then(data=>applyLocation({countryCode:data.country_code,locale:data.languages?.split(',')[0],label:[data.postal,data.city].filter(Boolean).join(' · ') || `Local prices · ${data.country_code}`})).catch(useLocale); if (!navigator.geolocation) { useIp(); return; } navigator.geolocation.getCurrentPosition(async position => { try { const response = await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${position.coords.latitude}&lon=${position.coords.longitude}`); const data = await response.json(); const address = data.address || {}; const countryCode = address.country_code?.toUpperCase() || 'US'; await applyLocation({countryCode,label:[address.postcode,address.city || address.town || address.village].filter(Boolean).join(' · ') || `Local prices · ${countryCode}`}); } catch { useIp(); } }, useIp, {enableHighAccuracy:false,timeout:8000}); setTimeout(()=>{button.disabled=false;},9000); }
window.addEventListener('storage',event=>{if(event.key===menuKey&&event.newValue){products=JSON.parse(event.newValue).filter(item=>item.available!==false).map(item=>({...item,desc:item.description||'',tag:item.tag||''}));renderProducts();updateCart()}});
async function hydrateCustomerMenu(){try{const remoteMenu=await supabaseReadMenu();if(!remoteMenu.length)return;products=remoteMenu.map(item=>({...item,desc:item.description||'',tag:item.tag||''}));renderProducts();updateCart()}catch(error){console.warn('Supabase menu unavailable; using local menu.',error.message)}}
supabaseWatchMenu(async()=>{await hydrateCustomerMenu()});
function renderProducts(category=activeCategory) { activeCategory=category; const search=($('#menuSearch')?.value || '').trim().toLowerCase(); const visible=products.filter(p=>(category==='all'||p.category===category)&&(!favoritesOnly||favorites.includes(p.id))&&(!search||`${p.name} ${p.desc}`.toLowerCase().includes(search))); $('#favoriteCount').textContent=favorites.length; $('#productGrid').innerHTML=visible.length ? visible.map(p => `<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="product-tag" ${p.tag?'':'hidden'}>${p.tag}</span><button class="favorite-btn ${favorites.includes(p.id)?'saved':''}" data-favorite="${p.id}" aria-label="${favorites.includes(p.id)?'Remove':'Save'} ${p.name} from favorites">${favorites.includes(p.id)?'♥':'♡'}</button><button class="add-btn" data-id="${p.id}" aria-label="Add ${p.name}">+</button></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><strong class="product-price">${locationState.marketPrices?.[p.id] ? localMoney(locationState.marketPrices[p.id]) : money(p.price)}</strong></div></article>`).join('') : '<div class="no-results"><strong>No crunch found.</strong><span>Try another search or browse the full menu.</span></div>'; }
function cartEntries(){ return Object.entries(cart).map(([id,quantity])=>({product:products.find(p=>p.id===id),quantity})).filter(x=>x.product); }
function updateCart(){ const entries=cartEntries(); const count=entries.reduce((sum,x)=>sum+x.quantity,0); const subtotal=entries.reduce((sum,x)=>sum+unitPrice(x.product)*x.quantity,0); const deliveryFee=2.99*locationState.rate; const discount=subtotal*discountRate; const total=subtotal ? subtotal+deliveryFee-discount : 0; $('#cartCount').textContent=count; $('#drawerCount').textContent=`(${count})`; $('#subtotal').textContent=localMoney(subtotal); $('#deliveryFee').textContent=localMoney(deliveryFee); $('#discount').textContent=`-${localMoney(discount)}`; $('#discountLine').style.display=discount?'flex':'none'; $('#total').textContent=localMoney(total); $('#checkoutTotal').textContent=localMoney(total); $('#cartSummary').style.display=entries.length?'block':'none'; $('#cartItems').innerHTML=entries.length ? entries.map(({product,quantity})=>`<div class="cart-row"><img src="${product.image}" alt=""><div><h4>${product.name}</h4><p>${product.desc}</p><div class="qty-control"><button data-qty="${product.id}" data-change="-1">−</button><span>${quantity}</span><button data-qty="${product.id}" data-change="1">+</button></div></div><strong>${localMoney(unitPrice(product)*quantity)}</strong></div>`).join('') : `<div class="empty-cart"><span>♧</span><h3>Your bag is empty</h3><p>Let's fix that. Add something delicious.</p><a href="#menu" id="browseMenu">Browse menu</a></div>`; localStorage.setItem('crisp-live-cart-v1',JSON.stringify(cart)); }
function addToCart(id, quantity=1){ const p=products.find(x=>x.id===id); if(!p)return; cart[id]=(cart[id]||0)+quantity; updateCart(); $('#toastText').textContent=`${p.name} · ${localMoney(unitPrice(p))}`; $('#toast').classList.add('show'); setTimeout(()=>$('#toast').classList.remove('show'),2300); }
function openCart(){ $('#cartDrawer').classList.add('open'); $('#overlay').classList.add('show'); document.body.style.overflow='hidden'; }
function closeCart(){ $('#cartDrawer').classList.remove('open'); $('#overlay').classList.remove('show'); document.body.style.overflow=''; }
async function publishSellerOrder(form,total){ const entries=cartEntries(); const firstName=String(form.get('firstName') || 'Guest'); const order={id:`#CRP-${Math.floor(1000+Math.random()*9000)}`,customer:firstName,initials:firstName.slice(0,2).toUpperCase(),items:entries.map(({product,quantity})=>`${quantity}x ${product.name}`).join(' · '),total:localMoney(total),status:'new',time:'Just now',address:`${form.get('address') || ''}, ${form.get('city') || ''} ${form.get('zip') || ''}`.trim(),currency:locationState.currency}; const sellerOrders=JSON.parse(localStorage.getItem('crisp-live-orders-v1') || '[]'); sellerOrders.unshift(order); localStorage.setItem('crisp-live-orders-v1',JSON.stringify(sellerOrders)); try{await supabaseSaveOrder(order)}catch(error){console.warn('Supabase order sync failed; local order retained.',error.message)} }
renderProducts(); updateCart(); hydrateCustomerMenu();
$('.category-tabs').addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;document.querySelectorAll('.category-tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');favoritesOnly=false;$('#favoritesFilter').classList.remove('active');renderProducts(btn.dataset.category)});
$('#menuSearch').addEventListener('input',()=>renderProducts());
$('#favoritesFilter').addEventListener('click',()=>{favoritesOnly=!favoritesOnly;$('#favoritesFilter').classList.toggle('active',favoritesOnly);renderProducts()});
$('#productGrid').addEventListener('click',e=>{const favorite=e.target.closest('[data-favorite]');if(favorite){const id=favorite.dataset.favorite;favorites=favorites.includes(id)?favorites.filter(item=>item!==id):[...favorites,id];localStorage.setItem('crisp-live-favorites-v1',JSON.stringify(favorites));renderProducts();return}const btn=e.target.closest('[data-id]');if(btn)addToCart(btn.dataset.id)});
$('#cartItems').addEventListener('click',e=>{const btn=e.target.closest('[data-qty]');if(!btn)return;const id=btn.dataset.qty;cart[id]=(cart[id]||0)+Number(btn.dataset.change);if(cart[id]<=0)delete cart[id];updateCart()});
$('#openCart').addEventListener('click',openCart); $('#closeCart').addEventListener('click',closeCart); $('#overlay').addEventListener('click',closeCart);
$('#cartItems').addEventListener('click',e=>{if(e.target.id==='browseMenu')closeCart()});
$('#applyPromo').addEventListener('click',()=>{const code=$('#promoCode').value.trim().toUpperCase();if(code==='CRUNCH10'){discountRate=.1;$('#promoMessage').textContent='Crunch10 applied · 10% off';$('#promoMessage').classList.add('valid')}else{discountRate=0;$('#promoMessage').textContent='Try CRUNCH10 for 10% off';$('#promoMessage').classList.remove('valid')}updateCart()});
document.querySelector('[data-add-deal]').addEventListener('click',()=>{if(products.length){addToCart(products[0].id);if(products[1])addToCart(products[1].id);openCart()}});
$('#checkoutBtn').addEventListener('click',()=>{if(!cartEntries().length)return;closeCart();$('#checkoutModal').classList.add('show');document.body.style.overflow='hidden'}); $('#closeCheckout').addEventListener('click',()=>{$('#checkoutModal').classList.remove('show');document.body.style.overflow=''});
document.querySelectorAll('.payment-choice').forEach(choice=>choice.addEventListener('click',()=>{document.querySelectorAll('.payment-choice').forEach(x=>x.classList.remove('active'));choice.classList.add('active')}));
$('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.target);const subtotal=cartEntries().reduce((sum,x)=>sum+unitPrice(x.product)*x.quantity,0);const total=subtotal+(2.99*locationState.rate)-(subtotal*discountRate);publishSellerOrder(form,total);$('#successName').textContent=`${form.get('firstName')} · ${form.get('zip')}`;$('#successTotal').textContent=localMoney(total);$('#checkoutModal').classList.remove('show');$('#successModal').classList.add('show');cart={};discountRate=0;updateCart();document.body.style.overflow='hidden'});
$('#doneBtn').addEventListener('click',()=>{$('#successModal').classList.remove('show');document.body.style.overflow='';window.scrollTo({top:0,behavior:'smooth'})});
$('#locationBtn').addEventListener('click',detectLocation);
$('#changeLocation').addEventListener('click',detectLocation);
$('#marketSelect').value = locationState.countryCode;
$('#marketSelect').addEventListener('change', event => { const countryCode = event.target.value; const entry = currencyFor(countryCode); applyLocation({countryCode,locale:entry.locale,label:countryCode === 'US' ? '10001 · New York, NY' : `Local prices · ${countryCode}`}); });
$('#locationBtn').innerHTML = `<span>⌖</span> ${locationState.label} <small>⌄</small>`;
$('#deliveryLocation').textContent = locationState.label;
