const menuKey='crisp-live-menu-v1';
const ordersKey='crisp-live-orders-v1';
const bookingsKey='crisp-live-bookings-v1';
const demoMenu=[{id:'demo-bucket',name:'Family Crunch Bucket',description:'8 pieces · 3 dips · feeds four',price:24.99,category:'chicken',image:'assets/bucket.jpg',available:true},{id:'demo-sando',name:'Smoky BBQ Sando',description:'Crispy chicken · BBQ glaze · slaw',price:12.49,category:'burgers',image:'assets/sando.jpg',available:true},{id:'demo-fries',name:'Seasoned Skin-On Fries',description:'Sea salt · house seasoning',price:4.99,category:'sides',image:'assets/fries.jpg',available:true}];
const demoOrders=[{id:'#DEMO-1003',customer:'Amina Cole',initials:'AC',items:'1x Family Crunch Bucket',total:'$24.99',status:'progress',time:'8 min ago'},{id:'#DEMO-1002',customer:'David Kim',initials:'DK',items:'2x Smoky BBQ Sando · 1x Fries',total:'$29.97',status:'new',time:'Just now'}];
const demoBookings=[{id:'DEMO-BK-01',name:'Nia Williams',initials:'NW',date:'18',month:'SEP',time:'19:30',guests:'4 guests',note:'Birthday dinner',status:'pending'},{id:'DEMO-BK-02',name:'Daniel Okafor',initials:'DO',date:'19',month:'SEP',time:'20:00',guests:'2 guests',note:'',status:'confirmed'}];
const hasLiveData=[menuKey,ordersKey,bookingsKey].some(key=>{try{return JSON.parse(localStorage.getItem(key)||'[]').length>0}catch{return false}});
if(!hasLiveData){localStorage.setItem(menuKey,JSON.stringify(demoMenu));localStorage.setItem(ordersKey,JSON.stringify(demoOrders));localStorage.setItem(bookingsKey,JSON.stringify(demoBookings))}
let menu=JSON.parse(localStorage.getItem(menuKey)||'[]');
let orders=JSON.parse(localStorage.getItem(ordersKey)||'[]');
let bookings=JSON.parse(localStorage.getItem(bookingsKey)||'[]');
const $=s=>document.querySelector(s); const money=v=>`$${Number(v).toFixed(2)}`;
function toast(text){$('#sellerToastText').textContent=text;$('#sellerToast').classList.add('show');setTimeout(()=>$('#sellerToast').classList.remove('show'),2200)}
function orderStatus(status){return status==='new'?'New':status==='progress'?'In progress':'Ready'}
function renderOrders(target='#overviewOrders',limit=3,filter='all'){const list=orders.filter(o=>filter==='all'||o.status===filter).slice(0,limit);$(target).innerHTML=list.map(o=>`<div class="order-row"><div class="order-avatar">${o.initials}</div><div class="order-meta"><strong>${o.id} · ${o.customer}</strong><small>${o.items} · ${o.time}</small></div><strong class="order-total">${o.total}</strong><span class="status-pill ${o.status==='ready'?'ready':o.status==='new'?'new':''}">${orderStatus(o.status)}</span>${target==='#fullOrderList'?`<div class="order-actions">${o.status==='new'?`<button class="small-button accept" data-order-action="accept" data-order-id="${o.id}">Accept</button>`:''}${o.status==='progress'?`<button class="small-button accept" data-order-action="ready" data-order-id="${o.id}">Mark ready</button>`:''}${o.status==='ready'?'<button class="small-button" disabled>Customer notified</button>':''}</div>`:''}</div>`).join('')||'<div class="empty-state">No orders in this view.</div>'}
function renderBookings(target='#overviewBookings',limit=2){const list=bookings.filter(b=>b.status==='pending').slice(0,limit);$(target).innerHTML=list.map(b=>`<div class="booking-row"><div class="booking-date"><small>${b.month}</small>${b.date}</div><div><strong>${b.name}</strong><small>${b.time} · ${b.guests}${b.note?` · ${b.note}`:''}</small></div><span class="status-pill">Needs confirmation</span>${target==='#bookingList'?`<div class="order-actions"><button class="small-button accept" data-booking-action="confirm" data-booking-id="${b.id}">Confirm</button><button class="small-button" data-booking-action="decline" data-booking-id="${b.id}">Decline</button></div>`:''}</div>`).join('')||'<div class="empty-state">All bookings are confirmed.</div>'}
function renderMenu(){ $('#menuCount').textContent=menu.filter(i=>i.available).length; $('#sellerMenuGrid').innerHTML=menu.map(item=>`<article class="seller-menu-card ${item.available?'':'unavailable'}"><img src="${item.image}" alt="${item.name}"><div class="seller-menu-copy"><h3>${item.name}</h3><p>${item.description}</p><strong>${money(item.price)}</strong><div class="card-menu-actions"><button data-menu-action="toggle" data-menu-id="${item.id}" title="Toggle availability">${item.available?'●':'○'}</button><button data-menu-action="delete" data-menu-id="${item.id}" title="Remove item">×</button></div></div></article>`).join('')}
function renderAll(){renderOrders();renderBookings();renderMenu();renderOrders('#fullOrderList',99);renderBookings('#bookingList',99);$('#orderNavCount').textContent=orders.filter(o=>o.status!=='ready').length;$('#bookingNavCount').textContent=bookings.filter(b=>b.status==='pending').length;$('#bookingsStat').textContent=bookings.filter(b=>b.status==='pending').length;$('#ordersStat').textContent=orders.length;$('#menuCount').textContent=menu.filter(i=>i.available).length;$('#salesStat').textContent=orders.length?'Recorded orders':'$0.00';localStorage.setItem(menuKey,JSON.stringify(menu));localStorage.setItem(ordersKey,JSON.stringify(orders));localStorage.setItem(bookingsKey,JSON.stringify(bookings));supabaseSaveMenu(menu).catch(error=>console.warn('Supabase menu sync failed; local menu retained.',error.message))}
async function hydrateSellerFromSupabase(){try{const [remoteMenu,remoteOrders]=await Promise.all([supabaseReadMenu(),supabaseReadOrders()]);if(remoteMenu.length)menu=remoteMenu;if(remoteOrders.length)orders=remoteOrders;renderAll()}catch(error){console.warn('Supabase seller data unavailable; using local data.',error.message)}}
supabaseWatchOrders(async()=>{try{const remoteOrders=await supabaseReadOrders();if(remoteOrders.length){orders=remoteOrders;renderAll();toast('Order queue updated')}}catch(error){console.warn('Supabase order update failed.',error.message)}});
window.addEventListener('storage',event=>{if(event.key===ordersKey&&event.newValue){orders=JSON.parse(event.newValue);renderAll();toast('New customer order received')}});
function switchView(view){document.querySelectorAll('.seller-view').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');document.querySelectorAll('.seller-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const title=view[0].toUpperCase()+view.slice(1);$('#viewLabel').textContent=title;$('#pageHeading').innerHTML=view==='overview'?'Good morning, Jordan <span>✦</span>':title;window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.seller-nav button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));document.querySelectorAll('[data-view-link]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.viewLink)));
document.querySelectorAll('[data-open-add]').forEach(button=>button.addEventListener('click',()=>$('#addModal').classList.add('show')));document.querySelector('[data-close-add]').addEventListener('click',()=>$('#addModal').classList.remove('show'));
$('#addFoodForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);menu.unshift({id:`custom-${Date.now()}`,name:data.get('name'),description:data.get('description'),price:Number(data.get('price')),category:data.get('category'),image:data.get('image'),available:data.get('available')==='on'});renderAll();event.target.reset();$('#addModal').classList.remove('show');toast('New menu item added')});
$('#sellerMenuGrid').addEventListener('click',event=>{const button=event.target.closest('[data-menu-action]');if(!button)return;const item=menu.find(i=>i.id===button.dataset.menuId);if(button.dataset.menuAction==='toggle')item.available=!item.available;if(button.dataset.menuAction==='delete')menu=menu.filter(i=>i.id!==button.dataset.menuId);renderAll();toast(button.dataset.menuAction==='toggle'?(item.available?'Item is live':'Item hidden from customers'):'Item removed')});
$('#fullOrderList').addEventListener('click',event=>{const button=event.target.closest('[data-order-action]');if(!button)return;const order=orders.find(o=>o.id===button.dataset.orderId);order.status=button.dataset.orderAction==='accept'?'progress':'ready';renderAll();supabaseSaveOrder(order).catch(error=>console.warn('Supabase order status sync failed.',error.message));toast(order.id+' updated to '+orderStatus(order.status))});
$('#bookingList').addEventListener('click',event=>{const button=event.target.closest('[data-booking-action]');if(!button)return;const booking=bookings.find(b=>b.id===button.dataset.bookingId);booking.status=button.dataset.bookingAction==='confirm'?'confirmed':'declined';renderAll();toast(booking.name+' booking '+booking.status)});
document.querySelectorAll('[data-order-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-order-filter]').forEach(b=>b.classList.remove('active'));button.classList.add('active');renderOrders('#fullOrderList',99,button.dataset.orderFilter)}));$('#menuVisibility').addEventListener('click',event=>{event.target.textContent=event.target.textContent.includes('Hide')?'Show menu to customers':'Hide menu temporarily';toast(event.target.textContent.includes('Show')?'Menu hidden':'Menu visible to customers')});$('#statusToggle').addEventListener('click',()=>toast('Store status controls are ready'));$('#newBooking').addEventListener('click',()=>toast('Booking form coming next'));
renderAll(); hydrateSellerFromSupabase();
